/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "ifcpp/Model/BasicTypes.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Ifc/IfcActorSelect.h"

// TYPE IfcActorSelect = SELECT	(IfcOrganization	,IfcPerson	,IfcPersonAndOrganization);
shared_ptr<IFC4X3::IfcActorSelect> IFC4X3::IfcActorSelect::createObjectFromSTEP( const std::string& arg, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	if( arg.empty() ){ return shared_ptr<IfcActorSelect>(); }
	if( arg.compare("$")==0 )
	{
		return shared_ptr<IfcActorSelect>();
	}
	if( arg.compare("*")==0 )
	{
		return shared_ptr<IfcActorSelect>();
	}
	shared_ptr<IfcActorSelect> result_object;
	readSelectType( arg, result_object, map, errorStream );
	return result_object;
}
