/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */

#include <sstream>
#include <limits>
#include <map>
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Writer/WriterUtil.h"
#include "ifcpp/Model/BasicTypes.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Ifc/IfcSimpleValue.h"
#include "ifcpp/Ifc/IfcBinary.h"

// TYPE IfcBinary = BINARY;
IFC4X3::IfcBinary::IfcBinary( std::string value ) { m_value = value; }
void IFC4X3::IfcBinary::getStepParameter( std::stringstream& stream, bool is_select_type ) const
{
	if( is_select_type ) { stream << "IFCBINARY("; }
	stream << "\"" << encodeStepString( m_value ) << "\"";
	if( is_select_type ) { stream << ")"; }
}
shared_ptr<IFC4X3::IfcBinary> IFC4X3::IfcBinary::createObjectFromSTEP( const std::string& arg, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	if( arg.compare( "$" ) == 0 ) { return shared_ptr<IfcBinary>(); }
	if( arg.compare( "*" ) == 0 ) { return shared_ptr<IfcBinary>(); }
	shared_ptr<IfcBinary> type_object( new IfcBinary() );
	readBinaryString( arg, type_object->m_value );
	return type_object;
}
