/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */

#include <sstream>
#include <limits>
#include <map>
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Writer/WriterUtil.h"
#include "ifcpp/Model/BasicTypes.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Ifc/IfcMeasureValue.h"
#include "ifcpp/Ifc/IfcCountMeasure.h"

// TYPE IfcCountMeasure = INTEGER;
IFC4X3::IfcCountMeasure::IfcCountMeasure( int value ) { m_value = value; }
void IFC4X3::IfcCountMeasure::getStepParameter( std::stringstream& stream, bool is_select_type ) const
{
	if( is_select_type ) { stream << "IFCCOUNTMEASURE("; }
	stream << m_value;
	if( is_select_type ) { stream << ")"; }
}
shared_ptr<IFC4X3::IfcCountMeasure> IFC4X3::IfcCountMeasure::createObjectFromSTEP( const std::string& arg, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	if( arg.compare( "$" ) == 0 ) { return shared_ptr<IfcCountMeasure>(); }
	if( arg.compare( "*" ) == 0 ) { return shared_ptr<IfcCountMeasure>(); }
	shared_ptr<IfcCountMeasure> type_object( new IfcCountMeasure() );
	readInteger( arg, type_object->m_value );
	return type_object;
}
