/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "ifcpp/Model/BasicTypes.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Ifc/IfcNormalisedRatioMeasure.h"
#include "ifcpp/Ifc/IfcColourOrFactor.h"

// TYPE IfcColourOrFactor = SELECT	(IfcColourRgb	,IfcNormalisedRatioMeasure);
shared_ptr<IFC4X3::IfcColourOrFactor> IFC4X3::IfcColourOrFactor::createObjectFromSTEP( const std::string& arg, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	if( arg.empty() ){ return shared_ptr<IfcColourOrFactor>(); }
	if( arg.compare("$")==0 )
	{
		return shared_ptr<IfcColourOrFactor>();
	}
	if( arg.compare("*")==0 )
	{
		return shared_ptr<IfcColourOrFactor>();
	}
	shared_ptr<IfcColourOrFactor> result_object;
	readSelectType( arg, result_object, map, errorStream );
	return result_object;
}
