/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "ifcpp/Model/BasicTypes.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Ifc/IfcCurveOnSurface.h"

// TYPE IfcCurveOnSurface = SELECT	(IfcCompositeCurveOnSurface	,IfcPcurve	,IfcSurfaceCurve);
shared_ptr<IFC4X3::IfcCurveOnSurface> IFC4X3::IfcCurveOnSurface::createObjectFromSTEP( const std::string& arg, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	if( arg.empty() ){ return shared_ptr<IfcCurveOnSurface>(); }
	if( arg.compare("$")==0 )
	{
		return shared_ptr<IfcCurveOnSurface>();
	}
	if( arg.compare("*")==0 )
	{
		return shared_ptr<IfcCurveOnSurface>();
	}
	shared_ptr<IfcCurveOnSurface> result_object;
	readSelectType( arg, result_object, map, errorStream );
	return result_object;
}
