/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <sstream>
#include <limits>

#include "ifcpp/Model/AttributeObject.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Model/BuildingGuid.h"
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Writer/WriterUtil.h"
#include "ifcpp/Ifc/IfcCompositeCurve.h"
#include "ifcpp/Ifc/IfcCurve.h"
#include "ifcpp/Ifc/IfcCurveMeasureSelect.h"
#include "ifcpp/Ifc/IfcCurveSegment.h"
#include "ifcpp/Ifc/IfcPlacement.h"
#include "ifcpp/Ifc/IfcPresentationLayerAssignment.h"
#include "ifcpp/Ifc/IfcStyledItem.h"
#include "ifcpp/Ifc/IfcTransitionCode.h"

// ENTITY IfcCurveSegment 
IFC4X3::IfcCurveSegment::IfcCurveSegment( int tag ) { m_tag = tag; }
void IFC4X3::IfcCurveSegment::getStepLine( std::stringstream& stream ) const
{
	stream << "#" << m_tag << "= IFCCURVESEGMENT" << "(";
	if( m_Transition ) { m_Transition->getStepParameter( stream ); } else { stream << "$"; }
	stream << ",";
	if( m_Placement ) { stream << "#" << m_Placement->m_tag; } else { stream << "$"; }
	stream << ",";
	if( m_SegmentStart ) { m_SegmentStart->getStepParameter( stream, true ); } else { stream << "$" ; }
	stream << ",";
	if( m_SegmentLength ) { m_SegmentLength->getStepParameter( stream, true ); } else { stream << "$" ; }
	stream << ",";
	if( m_ParentCurve ) { stream << "#" << m_ParentCurve->m_tag; } else { stream << "$"; }
	stream << ");";
}
void IFC4X3::IfcCurveSegment::getStepParameter( std::stringstream& stream, bool /*is_select_type*/ ) const { stream << "#" << m_tag; }
void IFC4X3::IfcCurveSegment::readStepArguments( const std::vector<std::string>& args, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	const size_t num_args = args.size();
	if( num_args != 5 ){ std::stringstream err; err << "Wrong parameter count for entity IfcCurveSegment, expecting 5, having " << num_args << ". Entity ID: " << m_tag << std::endl; throw BuildingException( err.str().c_str() ); }
	m_Transition = IfcTransitionCode::createObjectFromSTEP( args[0], map, errorStream );
	readEntityReference( args[1], m_Placement, map, errorStream );
	m_SegmentStart = IfcCurveMeasureSelect::createObjectFromSTEP( args[2], map, errorStream );
	m_SegmentLength = IfcCurveMeasureSelect::createObjectFromSTEP( args[3], map, errorStream );
	readEntityReference( args[4], m_ParentCurve, map, errorStream );
}
void IFC4X3::IfcCurveSegment::getAttributes( std::vector<std::pair<std::string, shared_ptr<BuildingObject> > >& vec_attributes ) const
{
	IFC4X3::IfcSegment::getAttributes( vec_attributes );
	vec_attributes.emplace_back( std::make_pair( "Placement", m_Placement ) );
	vec_attributes.emplace_back( std::make_pair( "SegmentStart", m_SegmentStart ) );
	vec_attributes.emplace_back( std::make_pair( "SegmentLength", m_SegmentLength ) );
	vec_attributes.emplace_back( std::make_pair( "ParentCurve", m_ParentCurve ) );
}
void IFC4X3::IfcCurveSegment::getAttributesInverse( std::vector<std::pair<std::string, shared_ptr<BuildingObject> > >& vec_attributes_inverse ) const
{
	IFC4X3::IfcSegment::getAttributesInverse( vec_attributes_inverse );
}
void IFC4X3::IfcCurveSegment::setInverseCounterparts( shared_ptr<BuildingEntity> ptr_self_entity )
{
	IfcSegment::setInverseCounterparts( ptr_self_entity );
}
void IFC4X3::IfcCurveSegment::unlinkFromInverseCounterparts()
{
	IfcSegment::unlinkFromInverseCounterparts();
}
