/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "ifcpp/Model/BasicTypes.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Ifc/IfcCurveFontOrScaledCurveFontSelect.h"
#include "ifcpp/Ifc/IfcCurveStyleFontSelect.h"

// TYPE IfcCurveStyleFontSelect = SELECT	(IfcCurveStyleFont	,IfcPreDefinedCurveFont);
shared_ptr<IFC4X3::IfcCurveStyleFontSelect> IFC4X3::IfcCurveStyleFontSelect::createObjectFromSTEP( const std::string& arg, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	if( arg.empty() ){ return shared_ptr<IfcCurveStyleFontSelect>(); }
	if( arg.compare("$")==0 )
	{
		return shared_ptr<IfcCurveStyleFontSelect>();
	}
	if( arg.compare("*")==0 )
	{
		return shared_ptr<IfcCurveStyleFontSelect>();
	}
	shared_ptr<IfcCurveStyleFontSelect> result_object;
	readSelectType( arg, result_object, map, errorStream );
	return result_object;
}
