/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "ifcpp/Model/BasicTypes.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Ifc/IfcClassificationReferenceSelect.h"

// TYPE IfcClassificationReferenceSelect = SELECT	(IfcClassification	,IfcClassificationReference);
shared_ptr<IFC4X3::IfcClassificationReferenceSelect> IFC4X3::IfcClassificationReferenceSelect::createObjectFromSTEP( const std::string& arg, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	if( arg.empty() ){ return shared_ptr<IfcClassificationReferenceSelect>(); }
	if( arg.compare("$")==0 )
	{
		return shared_ptr<IfcClassificationReferenceSelect>();
	}
	if( arg.compare("*")==0 )
	{
		return shared_ptr<IfcClassificationReferenceSelect>();
	}
	shared_ptr<IfcClassificationReferenceSelect> result_object;
	readSelectType( arg, result_object, map, errorStream );
	return result_object;
}
