/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "ifcpp/Model/BasicTypes.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Ifc/IfcFillStyleSelect.h"
#include "ifcpp/Ifc/IfcColour.h"

// TYPE IfcColour = SELECT	(IfcColourSpecification	,IfcPreDefinedColour);
shared_ptr<IFC4X3::IfcColour> IFC4X3::IfcColour::createObjectFromSTEP( const std::string& arg, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	if( arg.empty() ){ return shared_ptr<IfcColour>(); }
	if( arg.compare("$")==0 )
	{
		return shared_ptr<IfcColour>();
	}
	if( arg.compare("*")==0 )
	{
		return shared_ptr<IfcColour>();
	}
	shared_ptr<IfcColour> result_object;
	readSelectType( arg, result_object, map, errorStream );
	return result_object;
}
