/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "ifcpp/Model/BasicTypes.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Ifc/IfcCurveStyleFontSelect.h"
#include "ifcpp/Ifc/IfcCurveFontOrScaledCurveFontSelect.h"

// TYPE IfcCurveFontOrScaledCurveFontSelect = SELECT	(IfcCurveStyleFontAndScaling	,IfcCurveStyleFontSelect);
shared_ptr<IFC4X3::IfcCurveFontOrScaledCurveFontSelect> IFC4X3::IfcCurveFontOrScaledCurveFontSelect::createObjectFromSTEP( const std::string& arg, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	if( arg.empty() ){ return shared_ptr<IfcCurveFontOrScaledCurveFontSelect>(); }
	if( arg.compare("$")==0 )
	{
		return shared_ptr<IfcCurveFontOrScaledCurveFontSelect>();
	}
	if( arg.compare("*")==0 )
	{
		return shared_ptr<IfcCurveFontOrScaledCurveFontSelect>();
	}
	shared_ptr<IfcCurveFontOrScaledCurveFontSelect> result_object;
	readSelectType( arg, result_object, map, errorStream );
	return result_object;
}
