/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */

#include <sstream>
#include <limits>
#include <map>
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Writer/WriterUtil.h"
#include "ifcpp/Model/BasicTypes.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Ifc/IfcMeasureValue.h"
#include "ifcpp/Ifc/IfcSizeSelect.h"
#include "ifcpp/Ifc/IfcDescriptiveMeasure.h"

// TYPE IfcDescriptiveMeasure = STRING;
IFC4X3::IfcDescriptiveMeasure::IfcDescriptiveMeasure( std::string value ) { m_value = value; }
void IFC4X3::IfcDescriptiveMeasure::getStepParameter( std::stringstream& stream, bool is_select_type ) const
{
	if( is_select_type ) { stream << "IFCDESCRIPTIVEMEASURE("; }
	stream << "'" << encodeStepString( m_value ) << "'";
	if( is_select_type ) { stream << ")"; }
}
shared_ptr<IFC4X3::IfcDescriptiveMeasure> IFC4X3::IfcDescriptiveMeasure::createObjectFromSTEP( const std::string& arg, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	if( arg.compare( "$" ) == 0 ) { return shared_ptr<IfcDescriptiveMeasure>(); }
	if( arg.compare( "*" ) == 0 ) { return shared_ptr<IfcDescriptiveMeasure>(); }
	shared_ptr<IfcDescriptiveMeasure> type_object( new IfcDescriptiveMeasure() );
	readString( arg, type_object->m_value );
	return type_object;
}
