/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */

#include <sstream>
#include <limits>
#include <map>
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Writer/WriterUtil.h"
#include "ifcpp/Model/BasicTypes.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Ifc/IfcDimensionCount.h"

// TYPE IfcDimensionCount = INTEGER;
IFC4X3::IfcDimensionCount::IfcDimensionCount( int value ) { m_value = value; }
void IFC4X3::IfcDimensionCount::getStepParameter( std::stringstream& stream, bool is_select_type ) const
{
	if( is_select_type ) { stream << "IFCDIMENSIONCOUNT("; }
	stream << m_value;
	if( is_select_type ) { stream << ")"; }
}
shared_ptr<IFC4X3::IfcDimensionCount> IFC4X3::IfcDimensionCount::createObjectFromSTEP( const std::string& arg, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	if( arg.compare( "$" ) == 0 ) { return shared_ptr<IfcDimensionCount>(); }
	if( arg.compare( "*" ) == 0 ) { return shared_ptr<IfcDimensionCount>(); }
	shared_ptr<IfcDimensionCount> type_object( new IfcDimensionCount() );
	readInteger( arg, type_object->m_value );
	return type_object;
}
