/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <sstream>
#include <limits>

#include "ifcpp/Model/AttributeObject.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Model/BuildingGuid.h"
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Writer/WriterUtil.h"
#include "ifcpp/Ifc/IfcAxis2Placement3D.h"
#include "ifcpp/Ifc/IfcCurve.h"
#include "ifcpp/Ifc/IfcCurveMeasureSelect.h"
#include "ifcpp/Ifc/IfcDirection.h"
#include "ifcpp/Ifc/IfcDirectrixDerivedReferenceSweptAreaSolid.h"
#include "ifcpp/Ifc/IfcPresentationLayerAssignment.h"
#include "ifcpp/Ifc/IfcProfileDef.h"
#include "ifcpp/Ifc/IfcStyledItem.h"

// ENTITY IfcDirectrixDerivedReferenceSweptAreaSolid 
IFC4X3::IfcDirectrixDerivedReferenceSweptAreaSolid::IfcDirectrixDerivedReferenceSweptAreaSolid( int tag ) { m_tag = tag; }
void IFC4X3::IfcDirectrixDerivedReferenceSweptAreaSolid::getStepLine( std::stringstream& stream ) const
{
	stream << "#" << m_tag << "= IFCDIRECTRIXDERIVEDREFERENCESWEPTAREASOLID" << "(";
	if( m_SweptArea ) { stream << "#" << m_SweptArea->m_tag; } else { stream << "$"; }
	stream << ",";
	if( m_Position ) { stream << "#" << m_Position->m_tag; } else { stream << "$"; }
	stream << ",";
	if( m_Directrix ) { stream << "#" << m_Directrix->m_tag; } else { stream << "$"; }
	stream << ",";
	if( m_StartParam ) { m_StartParam->getStepParameter( stream, true ); } else { stream << "$" ; }
	stream << ",";
	if( m_EndParam ) { m_EndParam->getStepParameter( stream, true ); } else { stream << "$" ; }
	stream << ",";
	if( m_FixedReference ) { stream << "#" << m_FixedReference->m_tag; } else { stream << "$"; }
	stream << ");";
}
void IFC4X3::IfcDirectrixDerivedReferenceSweptAreaSolid::getStepParameter( std::stringstream& stream, bool /*is_select_type*/ ) const { stream << "#" << m_tag; }
void IFC4X3::IfcDirectrixDerivedReferenceSweptAreaSolid::readStepArguments( const std::vector<std::string>& args, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	const size_t num_args = args.size();
	if( num_args != 6 ){ std::stringstream err; err << "Wrong parameter count for entity IfcDirectrixDerivedReferenceSweptAreaSolid, expecting 6, having " << num_args << ". Entity ID: " << m_tag << std::endl; throw BuildingException( err.str().c_str() ); }
	readEntityReference( args[0], m_SweptArea, map, errorStream );
	readEntityReference( args[1], m_Position, map, errorStream );
	readEntityReference( args[2], m_Directrix, map, errorStream );
	m_StartParam = IfcCurveMeasureSelect::createObjectFromSTEP( args[3], map, errorStream );
	m_EndParam = IfcCurveMeasureSelect::createObjectFromSTEP( args[4], map, errorStream );
	readEntityReference( args[5], m_FixedReference, map, errorStream );
}
void IFC4X3::IfcDirectrixDerivedReferenceSweptAreaSolid::getAttributes( std::vector<std::pair<std::string, shared_ptr<BuildingObject> > >& vec_attributes ) const
{
	IFC4X3::IfcFixedReferenceSweptAreaSolid::getAttributes( vec_attributes );
}
void IFC4X3::IfcDirectrixDerivedReferenceSweptAreaSolid::getAttributesInverse( std::vector<std::pair<std::string, shared_ptr<BuildingObject> > >& vec_attributes_inverse ) const
{
	IFC4X3::IfcFixedReferenceSweptAreaSolid::getAttributesInverse( vec_attributes_inverse );
}
void IFC4X3::IfcDirectrixDerivedReferenceSweptAreaSolid::setInverseCounterparts( shared_ptr<BuildingEntity> ptr_self_entity )
{
	IfcFixedReferenceSweptAreaSolid::setInverseCounterparts( ptr_self_entity );
}
void IFC4X3::IfcDirectrixDerivedReferenceSweptAreaSolid::unlinkFromInverseCounterparts()
{
	IfcFixedReferenceSweptAreaSolid::unlinkFromInverseCounterparts();
}
