/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */

#include <sstream>
#include <limits>
#include <map>
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Writer/WriterUtil.h"
#include "ifcpp/Model/BasicTypes.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Ifc/IfcDerivedMeasureValue.h"
#include "ifcpp/Ifc/IfcElectricVoltageMeasure.h"

// TYPE IfcElectricVoltageMeasure = REAL;
IFC4X3::IfcElectricVoltageMeasure::IfcElectricVoltageMeasure( double value ) { m_value = value; }
void IFC4X3::IfcElectricVoltageMeasure::getStepParameter( std::stringstream& stream, bool is_select_type ) const
{
	if( is_select_type ) { stream << "IFCELECTRICVOLTAGEMEASURE("; }
	appendRealWithoutTrailingZeros( stream, m_value );
	if( is_select_type ) { stream << ")"; }
}
shared_ptr<IFC4X3::IfcElectricVoltageMeasure> IFC4X3::IfcElectricVoltageMeasure::createObjectFromSTEP( const std::string& arg, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	if( arg.compare( "$" ) == 0 ) { return shared_ptr<IfcElectricVoltageMeasure>(); }
	if( arg.compare( "*" ) == 0 ) { return shared_ptr<IfcElectricVoltageMeasure>(); }
	shared_ptr<IfcElectricVoltageMeasure> type_object( new IfcElectricVoltageMeasure() );
	readReal( arg, type_object->m_value );
	return type_object;
}
