/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "ifcpp/Model/BasicTypes.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Ifc/IfcPositiveLengthMeasure.h"
#include "ifcpp/Ifc/IfcHatchLineDistanceSelect.h"

// TYPE IfcHatchLineDistanceSelect = SELECT	(IfcPositiveLengthMeasure	,IfcVector);
shared_ptr<IFC4X3::IfcHatchLineDistanceSelect> IFC4X3::IfcHatchLineDistanceSelect::createObjectFromSTEP( const std::string& arg, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	if( arg.empty() ){ return shared_ptr<IfcHatchLineDistanceSelect>(); }
	if( arg.compare("$")==0 )
	{
		return shared_ptr<IfcHatchLineDistanceSelect>();
	}
	if( arg.compare("*")==0 )
	{
		return shared_ptr<IfcHatchLineDistanceSelect>();
	}
	shared_ptr<IfcHatchLineDistanceSelect> result_object;
	readSelectType( arg, result_object, map, errorStream );
	return result_object;
}
