/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "ifcpp/Model/BasicTypes.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Ifc/IfcInterferenceSelect.h"

// TYPE IfcInterferenceSelect = SELECT	(IfcElement	,IfcSpatialElement);
shared_ptr<IFC4X3::IfcInterferenceSelect> IFC4X3::IfcInterferenceSelect::createObjectFromSTEP( const std::string& arg, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	if( arg.empty() ){ return shared_ptr<IfcInterferenceSelect>(); }
	if( arg.compare("$")==0 )
	{
		return shared_ptr<IfcInterferenceSelect>();
	}
	if( arg.compare("*")==0 )
	{
		return shared_ptr<IfcInterferenceSelect>();
	}
	shared_ptr<IfcInterferenceSelect> result_object;
	readSelectType( arg, result_object, map, errorStream );
	return result_object;
}
