/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "ifcpp/Model/BasicTypes.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Ifc/IfcBoolean.h"
#include "ifcpp/Ifc/IfcModulusOfSubgradeReactionMeasure.h"
#include "ifcpp/Ifc/IfcModulusOfSubgradeReactionSelect.h"

// TYPE IfcModulusOfSubgradeReactionSelect = SELECT	(IfcBoolean	,IfcModulusOfSubgradeReactionMeasure);
shared_ptr<IFC4X3::IfcModulusOfSubgradeReactionSelect> IFC4X3::IfcModulusOfSubgradeReactionSelect::createObjectFromSTEP( const std::string& arg, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	if( arg.empty() ){ return shared_ptr<IfcModulusOfSubgradeReactionSelect>(); }
	if( arg.compare("$")==0 )
	{
		return shared_ptr<IfcModulusOfSubgradeReactionSelect>();
	}
	if( arg.compare("*")==0 )
	{
		return shared_ptr<IfcModulusOfSubgradeReactionSelect>();
	}
	shared_ptr<IfcModulusOfSubgradeReactionSelect> result_object;
	readSelectType( arg, result_object, map, errorStream );
	return result_object;
}
