/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <sstream>
#include <limits>

#include "ifcpp/Model/AttributeObject.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Model/BuildingGuid.h"
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Writer/WriterUtil.h"
#include "ifcpp/Ifc/IfcExternalReferenceRelationship.h"
#include "ifcpp/Ifc/IfcInteger.h"
#include "ifcpp/Ifc/IfcLabel.h"
#include "ifcpp/Ifc/IfcLayerSetDirectionEnum.h"
#include "ifcpp/Ifc/IfcLengthMeasure.h"
#include "ifcpp/Ifc/IfcLogical.h"
#include "ifcpp/Ifc/IfcMaterial.h"
#include "ifcpp/Ifc/IfcMaterialLayerSet.h"
#include "ifcpp/Ifc/IfcMaterialLayerWithOffsets.h"
#include "ifcpp/Ifc/IfcMaterialProperties.h"
#include "ifcpp/Ifc/IfcNonNegativeLengthMeasure.h"
#include "ifcpp/Ifc/IfcRelAssociatesMaterial.h"
#include "ifcpp/Ifc/IfcText.h"

// ENTITY IfcMaterialLayerWithOffsets 
IFC4X3::IfcMaterialLayerWithOffsets::IfcMaterialLayerWithOffsets( int tag ) { m_tag = tag; }
void IFC4X3::IfcMaterialLayerWithOffsets::getStepLine( std::stringstream& stream ) const
{
	stream << "#" << m_tag << "= IFCMATERIALLAYERWITHOFFSETS" << "(";
	if( m_Material ) { stream << "#" << m_Material->m_tag; } else { stream << "$"; }
	stream << ",";
	if( m_LayerThickness ) { m_LayerThickness->getStepParameter( stream ); } else { stream << "$"; }
	stream << ",";
	if( m_IsVentilated ) { m_IsVentilated->getStepParameter( stream ); } else { stream << "$"; }
	stream << ",";
	if( m_Name ) { m_Name->getStepParameter( stream ); } else { stream << "$"; }
	stream << ",";
	if( m_Description ) { m_Description->getStepParameter( stream ); } else { stream << "$"; }
	stream << ",";
	if( m_Category ) { m_Category->getStepParameter( stream ); } else { stream << "$"; }
	stream << ",";
	if( m_Priority ) { m_Priority->getStepParameter( stream ); } else { stream << "$"; }
	stream << ",";
	if( m_OffsetDirection ) { m_OffsetDirection->getStepParameter( stream ); } else { stream << "$"; }
	stream << ",";
	writeTypeOfRealList( stream, m_OffsetValues, false );
	stream << ");";
}
void IFC4X3::IfcMaterialLayerWithOffsets::getStepParameter( std::stringstream& stream, bool /*is_select_type*/ ) const { stream << "#" << m_tag; }
void IFC4X3::IfcMaterialLayerWithOffsets::readStepArguments( const std::vector<std::string>& args, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	const size_t num_args = args.size();
	if( num_args != 9 ){ std::stringstream err; err << "Wrong parameter count for entity IfcMaterialLayerWithOffsets, expecting 9, having " << num_args << ". Entity ID: " << m_tag << std::endl; throw BuildingException( err.str().c_str() ); }
	readEntityReference( args[0], m_Material, map, errorStream );
	m_LayerThickness = IfcNonNegativeLengthMeasure::createObjectFromSTEP( args[1], map, errorStream );
	m_IsVentilated = IfcLogical::createObjectFromSTEP( args[2], map, errorStream );
	m_Name = IfcLabel::createObjectFromSTEP( args[3], map, errorStream );
	m_Description = IfcText::createObjectFromSTEP( args[4], map, errorStream );
	m_Category = IfcLabel::createObjectFromSTEP( args[5], map, errorStream );
	m_Priority = IfcInteger::createObjectFromSTEP( args[6], map, errorStream );
	m_OffsetDirection = IfcLayerSetDirectionEnum::createObjectFromSTEP( args[7], map, errorStream );
	readTypeOfRealList( args[8], m_OffsetValues );
}
void IFC4X3::IfcMaterialLayerWithOffsets::getAttributes( std::vector<std::pair<std::string, shared_ptr<BuildingObject> > >& vec_attributes ) const
{
	IFC4X3::IfcMaterialLayer::getAttributes( vec_attributes );
	vec_attributes.emplace_back( std::make_pair( "OffsetDirection", m_OffsetDirection ) );
	if( !m_OffsetValues.empty() )
	{
		shared_ptr<AttributeObjectVector> OffsetValues_vec_object( new AttributeObjectVector() );
		std::copy( m_OffsetValues.begin(), m_OffsetValues.end(), std::back_inserter( OffsetValues_vec_object->m_vec ) );
		vec_attributes.emplace_back( std::make_pair( "OffsetValues", OffsetValues_vec_object ) );
	}
}
void IFC4X3::IfcMaterialLayerWithOffsets::getAttributesInverse( std::vector<std::pair<std::string, shared_ptr<BuildingObject> > >& vec_attributes_inverse ) const
{
	IFC4X3::IfcMaterialLayer::getAttributesInverse( vec_attributes_inverse );
}
void IFC4X3::IfcMaterialLayerWithOffsets::setInverseCounterparts( shared_ptr<BuildingEntity> ptr_self_entity )
{
	IfcMaterialLayer::setInverseCounterparts( ptr_self_entity );
}
void IFC4X3::IfcMaterialLayerWithOffsets::unlinkFromInverseCounterparts()
{
	IfcMaterialLayer::unlinkFromInverseCounterparts();
}
