/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */

#include <sstream>
#include <limits>
#include <map>
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Writer/WriterUtil.h"
#include "ifcpp/Model/BasicTypes.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Ifc/IfcMonthInYearNumber.h"

// TYPE IfcMonthInYearNumber = INTEGER;
IFC4X3::IfcMonthInYearNumber::IfcMonthInYearNumber( int value ) { m_value = value; }
void IFC4X3::IfcMonthInYearNumber::getStepParameter( std::stringstream& stream, bool is_select_type ) const
{
	if( is_select_type ) { stream << "IFCMONTHINYEARNUMBER("; }
	stream << m_value;
	if( is_select_type ) { stream << ")"; }
}
shared_ptr<IFC4X3::IfcMonthInYearNumber> IFC4X3::IfcMonthInYearNumber::createObjectFromSTEP( const std::string& arg, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	if( arg.compare( "$" ) == 0 ) { return shared_ptr<IfcMonthInYearNumber>(); }
	if( arg.compare( "*" ) == 0 ) { return shared_ptr<IfcMonthInYearNumber>(); }
	shared_ptr<IfcMonthInYearNumber> type_object( new IfcMonthInYearNumber() );
	readInteger( arg, type_object->m_value );
	return type_object;
}
