/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "ifcpp/Model/BasicTypes.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Ifc/IfcBoolean.h"
#include "ifcpp/Ifc/IfcModulusOfRotationalSubgradeReactionMeasure.h"
#include "ifcpp/Ifc/IfcModulusOfRotationalSubgradeReactionSelect.h"

// TYPE IfcModulusOfRotationalSubgradeReactionSelect = SELECT	(IfcBoolean	,IfcModulusOfRotationalSubgradeReactionMeasure);
shared_ptr<IFC4X3::IfcModulusOfRotationalSubgradeReactionSelect> IFC4X3::IfcModulusOfRotationalSubgradeReactionSelect::createObjectFromSTEP( const std::string& arg, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	if( arg.empty() ){ return shared_ptr<IfcModulusOfRotationalSubgradeReactionSelect>(); }
	if( arg.compare("$")==0 )
	{
		return shared_ptr<IfcModulusOfRotationalSubgradeReactionSelect>();
	}
	if( arg.compare("*")==0 )
	{
		return shared_ptr<IfcModulusOfRotationalSubgradeReactionSelect>();
	}
	shared_ptr<IfcModulusOfRotationalSubgradeReactionSelect> result_object;
	readSelectType( arg, result_object, map, errorStream );
	return result_object;
}
