/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "ifcpp/Model/BasicTypes.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Ifc/IfcObjectReferenceSelect.h"

// TYPE IfcObjectReferenceSelect = SELECT	(IfcAddress	,IfcAppliedValue	,IfcExternalReference	,IfcMaterialDefinition	,IfcOrganization	,IfcPerson	,IfcPersonAndOrganization	,IfcTable	,IfcTimeSeries);
shared_ptr<IFC4X3::IfcObjectReferenceSelect> IFC4X3::IfcObjectReferenceSelect::createObjectFromSTEP( const std::string& arg, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	if( arg.empty() ){ return shared_ptr<IfcObjectReferenceSelect>(); }
	if( arg.compare("$")==0 )
	{
		return shared_ptr<IfcObjectReferenceSelect>();
	}
	if( arg.compare("*")==0 )
	{
		return shared_ptr<IfcObjectReferenceSelect>();
	}
	shared_ptr<IfcObjectReferenceSelect> result_object;
	readSelectType( arg, result_object, map, errorStream );
	return result_object;
}
