/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <sstream>
#include <limits>

#include "ifcpp/Model/AttributeObject.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Model/BuildingGuid.h"
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Writer/WriterUtil.h"
#include "ifcpp/Ifc/IfcBoolean.h"
#include "ifcpp/Ifc/IfcEdge.h"
#include "ifcpp/Ifc/IfcOrientedEdge.h"
#include "ifcpp/Ifc/IfcPresentationLayerAssignment.h"
#include "ifcpp/Ifc/IfcStyledItem.h"
#include "ifcpp/Ifc/IfcVertex.h"

// ENTITY IfcOrientedEdge 
IFC4X3::IfcOrientedEdge::IfcOrientedEdge( int tag ) { m_tag = tag; }
void IFC4X3::IfcOrientedEdge::getStepLine( std::stringstream& stream ) const
{
	stream << "#" << m_tag << "= IFCORIENTEDEDGE" << "(";
	if( m_EdgeStart ) { stream << "#" << m_EdgeStart->m_tag; } else { stream << "*"; }
	stream << ",";
	if( m_EdgeEnd ) { stream << "#" << m_EdgeEnd->m_tag; } else { stream << "*"; }
	stream << ",";
	if( m_EdgeElement ) { stream << "#" << m_EdgeElement->m_tag; } else { stream << "$"; }
	stream << ",";
	if( m_Orientation ) { m_Orientation->getStepParameter( stream ); } else { stream << "$"; }
	stream << ");";
}
void IFC4X3::IfcOrientedEdge::getStepParameter( std::stringstream& stream, bool /*is_select_type*/ ) const { stream << "#" << m_tag; }
void IFC4X3::IfcOrientedEdge::readStepArguments( const std::vector<std::string>& args, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	const size_t num_args = args.size();
	if( num_args != 4 ){ std::stringstream err; err << "Wrong parameter count for entity IfcOrientedEdge, expecting 4, having " << num_args << ". Entity ID: " << m_tag << std::endl; throw BuildingException( err.str().c_str() ); }
	readEntityReference( args[0], m_EdgeStart, map, errorStream );
	readEntityReference( args[1], m_EdgeEnd, map, errorStream );
	readEntityReference( args[2], m_EdgeElement, map, errorStream );
	m_Orientation = IfcBoolean::createObjectFromSTEP( args[3], map, errorStream );
}
void IFC4X3::IfcOrientedEdge::getAttributes( std::vector<std::pair<std::string, shared_ptr<BuildingObject> > >& vec_attributes ) const
{
	IFC4X3::IfcEdge::getAttributes( vec_attributes );
	vec_attributes.emplace_back( std::make_pair( "EdgeElement", m_EdgeElement ) );
	vec_attributes.emplace_back( std::make_pair( "Orientation", m_Orientation ) );
}
void IFC4X3::IfcOrientedEdge::getAttributesInverse( std::vector<std::pair<std::string, shared_ptr<BuildingObject> > >& vec_attributes_inverse ) const
{
	IFC4X3::IfcEdge::getAttributesInverse( vec_attributes_inverse );
}
void IFC4X3::IfcOrientedEdge::setInverseCounterparts( shared_ptr<BuildingEntity> ptr_self_entity )
{
	IfcEdge::setInverseCounterparts( ptr_self_entity );
}
void IFC4X3::IfcOrientedEdge::unlinkFromInverseCounterparts()
{
	IfcEdge::unlinkFromInverseCounterparts();
}
