/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <sstream>
#include <limits>

#include "ifcpp/Model/AttributeObject.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Model/BuildingGuid.h"
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Writer/WriterUtil.h"
#include "ifcpp/Ifc/IfcPresentationItem.h"

// ENTITY IfcPresentationItem 
IFC4X3::IfcPresentationItem::IfcPresentationItem( int tag ) { m_tag = tag; }
void IFC4X3::IfcPresentationItem::getStepLine( std::stringstream& stream ) const
{
	stream << "#" << m_tag << "= IFCPRESENTATIONITEM" << "(";
	stream << ");";
}
void IFC4X3::IfcPresentationItem::getStepParameter( std::stringstream& stream, bool /*is_select_type*/ ) const { stream << "#" << m_tag; }
void IFC4X3::IfcPresentationItem::readStepArguments( const std::vector<std::string>& args, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
}
void IFC4X3::IfcPresentationItem::getAttributes( std::vector<std::pair<std::string, shared_ptr<BuildingObject> > >& vec_attributes ) const
{
}
void IFC4X3::IfcPresentationItem::getAttributesInverse( std::vector<std::pair<std::string, shared_ptr<BuildingObject> > >& vec_attributes_inverse ) const
{
}
void IFC4X3::IfcPresentationItem::setInverseCounterparts( shared_ptr<BuildingEntity> )
{
}
void IFC4X3::IfcPresentationItem::unlinkFromInverseCounterparts()
{
}
