/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */

#include <sstream>
#include <limits>
#include <map>
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Writer/WriterUtil.h"
#include "ifcpp/Model/BasicTypes.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Ifc/IfcCurveMeasureSelect.h"
#include "ifcpp/Ifc/IfcMeasureValue.h"
#include "ifcpp/Ifc/IfcTrimmingSelect.h"
#include "ifcpp/Ifc/IfcParameterValue.h"

// TYPE IfcParameterValue = REAL;
IFC4X3::IfcParameterValue::IfcParameterValue( double value ) { m_value = value; }
void IFC4X3::IfcParameterValue::getStepParameter( std::stringstream& stream, bool is_select_type ) const
{
	if( is_select_type ) { stream << "IFCPARAMETERVALUE("; }
	appendRealWithoutTrailingZeros( stream, m_value );
	if( is_select_type ) { stream << ")"; }
}
shared_ptr<IFC4X3::IfcParameterValue> IFC4X3::IfcParameterValue::createObjectFromSTEP( const std::string& arg, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	if( arg.compare( "$" ) == 0 ) { return shared_ptr<IfcParameterValue>(); }
	if( arg.compare( "*" ) == 0 ) { return shared_ptr<IfcParameterValue>(); }
	shared_ptr<IfcParameterValue> type_object( new IfcParameterValue() );
	readReal( arg, type_object->m_value );
	return type_object;
}
