/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "ifcpp/Model/BasicTypes.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Ifc/IfcProcessSelect.h"

// TYPE IfcProcessSelect = SELECT	(IfcProcess	,IfcTypeProcess);
shared_ptr<IFC4X3::IfcProcessSelect> IFC4X3::IfcProcessSelect::createObjectFromSTEP( const std::string& arg, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	if( arg.empty() ){ return shared_ptr<IfcProcessSelect>(); }
	if( arg.compare("$")==0 )
	{
		return shared_ptr<IfcProcessSelect>();
	}
	if( arg.compare("*")==0 )
	{
		return shared_ptr<IfcProcessSelect>();
	}
	shared_ptr<IfcProcessSelect> result_object;
	readSelectType( arg, result_object, map, errorStream );
	return result_object;
}
