/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */

#include <sstream>
#include <limits>
#include <map>
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Writer/WriterUtil.h"
#include "ifcpp/Model/BasicTypes.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Ifc/IfcSimpleValue.h"
#include "ifcpp/Ifc/IfcPositiveInteger.h"

// TYPE IfcPositiveInteger = IfcInteger;
void IFC4X3::IfcPositiveInteger::getStepParameter( std::stringstream& stream, bool is_select_type ) const
{
	if( is_select_type ) { stream << "IFCPOSITIVEINTEGER("; }
	stream << m_value;
	if( is_select_type ) { stream << ")"; }
}
shared_ptr<IFC4X3::IfcPositiveInteger> IFC4X3::IfcPositiveInteger::createObjectFromSTEP( const std::string& arg, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	if( arg.compare( "$" ) == 0 ) { return shared_ptr<IfcPositiveInteger>(); }
	if( arg.compare( "*" ) == 0 ) { return shared_ptr<IfcPositiveInteger>(); }
	shared_ptr<IfcPositiveInteger> type_object( new IfcPositiveInteger() );
	readInteger( arg, type_object->m_value );
	return type_object;
}
