/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <sstream>
#include <limits>

#include "ifcpp/Model/AttributeObject.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Model/BuildingGuid.h"
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Writer/WriterUtil.h"
#include "ifcpp/Ifc/IfcAxis2Placement.h"
#include "ifcpp/Ifc/IfcLengthMeasure.h"
#include "ifcpp/Ifc/IfcPlanarBox.h"
#include "ifcpp/Ifc/IfcPresentationLayerAssignment.h"
#include "ifcpp/Ifc/IfcStyledItem.h"

// ENTITY IfcPlanarBox 
IFC4X3::IfcPlanarBox::IfcPlanarBox( int tag ) { m_tag = tag; }
void IFC4X3::IfcPlanarBox::getStepLine( std::stringstream& stream ) const
{
	stream << "#" << m_tag << "= IFCPLANARBOX" << "(";
	if( m_SizeInX ) { m_SizeInX->getStepParameter( stream ); } else { stream << "$"; }
	stream << ",";
	if( m_SizeInY ) { m_SizeInY->getStepParameter( stream ); } else { stream << "$"; }
	stream << ",";
	if( m_Placement ) { m_Placement->getStepParameter( stream, true ); } else { stream << "$" ; }
	stream << ");";
}
void IFC4X3::IfcPlanarBox::getStepParameter( std::stringstream& stream, bool /*is_select_type*/ ) const { stream << "#" << m_tag; }
void IFC4X3::IfcPlanarBox::readStepArguments( const std::vector<std::string>& args, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	const size_t num_args = args.size();
	if( num_args != 3 ){ std::stringstream err; err << "Wrong parameter count for entity IfcPlanarBox, expecting 3, having " << num_args << ". Entity ID: " << m_tag << std::endl; throw BuildingException( err.str().c_str() ); }
	m_SizeInX = IfcLengthMeasure::createObjectFromSTEP( args[0], map, errorStream );
	m_SizeInY = IfcLengthMeasure::createObjectFromSTEP( args[1], map, errorStream );
	m_Placement = IfcAxis2Placement::createObjectFromSTEP( args[2], map, errorStream );
}
void IFC4X3::IfcPlanarBox::getAttributes( std::vector<std::pair<std::string, shared_ptr<BuildingObject> > >& vec_attributes ) const
{
	IFC4X3::IfcPlanarExtent::getAttributes( vec_attributes );
	vec_attributes.emplace_back( std::make_pair( "Placement", m_Placement ) );
}
void IFC4X3::IfcPlanarBox::getAttributesInverse( std::vector<std::pair<std::string, shared_ptr<BuildingObject> > >& vec_attributes_inverse ) const
{
	IFC4X3::IfcPlanarExtent::getAttributesInverse( vec_attributes_inverse );
}
void IFC4X3::IfcPlanarBox::setInverseCounterparts( shared_ptr<BuildingEntity> ptr_self_entity )
{
	IfcPlanarExtent::setInverseCounterparts( ptr_self_entity );
}
void IFC4X3::IfcPlanarBox::unlinkFromInverseCounterparts()
{
	IfcPlanarExtent::unlinkFromInverseCounterparts();
}
