/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */

#include <sstream>
#include <limits>
#include <map>
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Writer/WriterUtil.h"
#include "ifcpp/Model/BasicTypes.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Ifc/IfcRailwayTypeEnum.h"

// TYPE IfcRailwayTypeEnum = ENUMERATION OF	(USERDEFINED	,NOTDEFINED);
void IFC4X3::IfcRailwayTypeEnum::getStepParameter( std::stringstream& stream, bool is_select_type ) const
{
	if( is_select_type ) { stream << "IFCRAILWAYTYPEENUM("; }
	switch( m_enum )
	{
		case ENUM_USERDEFINED:	stream << ".USERDEFINED."; break;
		case ENUM_NOTDEFINED:	stream << ".NOTDEFINED."; break;
	}
	if( is_select_type ) { stream << ")"; }
}
shared_ptr<IFC4X3::IfcRailwayTypeEnum> IFC4X3::IfcRailwayTypeEnum::createObjectFromSTEP( const std::string& arg, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	if( arg.compare( "$" ) == 0 ) { return shared_ptr<IfcRailwayTypeEnum>(); }
	if( arg.compare( "*" ) == 0 ) { return shared_ptr<IfcRailwayTypeEnum>(); }
	shared_ptr<IfcRailwayTypeEnum> type_object( new IfcRailwayTypeEnum() );
	if( std_iequal( arg, ".USERDEFINED." ) )
	{
		type_object->m_enum = IfcRailwayTypeEnum::ENUM_USERDEFINED;
	}
	else if( std_iequal( arg, ".NOTDEFINED." ) )
	{
		type_object->m_enum = IfcRailwayTypeEnum::ENUM_NOTDEFINED;
	}
	return type_object;
}
