/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "ifcpp/Model/BasicTypes.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Ifc/IfcBoolean.h"
#include "ifcpp/Ifc/IfcRotationalStiffnessMeasure.h"
#include "ifcpp/Ifc/IfcRotationalStiffnessSelect.h"

// TYPE IfcRotationalStiffnessSelect = SELECT	(IfcBoolean	,IfcRotationalStiffnessMeasure);
shared_ptr<IFC4X3::IfcRotationalStiffnessSelect> IFC4X3::IfcRotationalStiffnessSelect::createObjectFromSTEP( const std::string& arg, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	if( arg.empty() ){ return shared_ptr<IfcRotationalStiffnessSelect>(); }
	if( arg.compare("$")==0 )
	{
		return shared_ptr<IfcRotationalStiffnessSelect>();
	}
	if( arg.compare("*")==0 )
	{
		return shared_ptr<IfcRotationalStiffnessSelect>();
	}
	shared_ptr<IfcRotationalStiffnessSelect> result_object;
	readSelectType( arg, result_object, map, errorStream );
	return result_object;
}
