/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <sstream>
#include <limits>

#include "ifcpp/Model/AttributeObject.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Model/BuildingGuid.h"
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Writer/WriterUtil.h"
#include "ifcpp/Ifc/IfcPresentationLayerAssignment.h"
#include "ifcpp/Ifc/IfcRepresentationItem.h"
#include "ifcpp/Ifc/IfcStyledItem.h"

// ENTITY IfcRepresentationItem 
IFC4X3::IfcRepresentationItem::IfcRepresentationItem( int tag ) { m_tag = tag; }
void IFC4X3::IfcRepresentationItem::getStepLine( std::stringstream& stream ) const
{
	stream << "#" << m_tag << "= IFCREPRESENTATIONITEM" << "(";
	stream << ");";
}
void IFC4X3::IfcRepresentationItem::getStepParameter( std::stringstream& stream, bool /*is_select_type*/ ) const { stream << "#" << m_tag; }
void IFC4X3::IfcRepresentationItem::readStepArguments( const std::vector<std::string>& args, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
}
void IFC4X3::IfcRepresentationItem::getAttributes( std::vector<std::pair<std::string, shared_ptr<BuildingObject> > >& vec_attributes ) const
{
}
void IFC4X3::IfcRepresentationItem::getAttributesInverse( std::vector<std::pair<std::string, shared_ptr<BuildingObject> > >& vec_attributes_inverse ) const
{
	if( !m_LayerAssignment_inverse.empty() )
	{
		shared_ptr<AttributeObjectVector> LayerAssignment_inverse_vec_obj( new AttributeObjectVector() );
		for( size_t i=0; i<m_LayerAssignment_inverse.size(); ++i )
		{
			if( !m_LayerAssignment_inverse[i].expired() )
			{
				LayerAssignment_inverse_vec_obj->m_vec.emplace_back( shared_ptr<IfcPresentationLayerAssignment>( m_LayerAssignment_inverse[i] ) );
			}
		}
		vec_attributes_inverse.emplace_back( std::make_pair( "LayerAssignment_inverse", LayerAssignment_inverse_vec_obj ) );
	}
	if( !m_StyledByItem_inverse.empty() )
	{
		shared_ptr<AttributeObjectVector> StyledByItem_inverse_vec_obj( new AttributeObjectVector() );
		for( size_t i=0; i<m_StyledByItem_inverse.size(); ++i )
		{
			if( !m_StyledByItem_inverse[i].expired() )
			{
				StyledByItem_inverse_vec_obj->m_vec.emplace_back( shared_ptr<IfcStyledItem>( m_StyledByItem_inverse[i] ) );
			}
		}
		vec_attributes_inverse.emplace_back( std::make_pair( "StyledByItem_inverse", StyledByItem_inverse_vec_obj ) );
	}
}
void IFC4X3::IfcRepresentationItem::setInverseCounterparts( shared_ptr<BuildingEntity> )
{
}
void IFC4X3::IfcRepresentationItem::unlinkFromInverseCounterparts()
{
}
