/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "ifcpp/Model/BasicTypes.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Ifc/IfcSurfaceOrFaceSurface.h"

// TYPE IfcSurfaceOrFaceSurface = SELECT	(IfcFaceBasedSurfaceModel	,IfcFaceSurface	,IfcSurface);
shared_ptr<IFC4X3::IfcSurfaceOrFaceSurface> IFC4X3::IfcSurfaceOrFaceSurface::createObjectFromSTEP( const std::string& arg, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	if( arg.empty() ){ return shared_ptr<IfcSurfaceOrFaceSurface>(); }
	if( arg.compare("$")==0 )
	{
		return shared_ptr<IfcSurfaceOrFaceSurface>();
	}
	if( arg.compare("*")==0 )
	{
		return shared_ptr<IfcSurfaceOrFaceSurface>();
	}
	shared_ptr<IfcSurfaceOrFaceSurface> result_object;
	readSelectType( arg, result_object, map, errorStream );
	return result_object;
}
