/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <sstream>
#include <limits>

#include "ifcpp/Model/AttributeObject.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Model/BuildingGuid.h"
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Writer/WriterUtil.h"
#include "ifcpp/Ifc/IfcBoundedCurve.h"
#include "ifcpp/Ifc/IfcLogical.h"
#include "ifcpp/Ifc/IfcPlacement.h"
#include "ifcpp/Ifc/IfcPresentationLayerAssignment.h"
#include "ifcpp/Ifc/IfcSegment.h"
#include "ifcpp/Ifc/IfcSegmentedReferenceCurve.h"
#include "ifcpp/Ifc/IfcStyledItem.h"

// ENTITY IfcSegmentedReferenceCurve 
IFC4X3::IfcSegmentedReferenceCurve::IfcSegmentedReferenceCurve( int tag ) { m_tag = tag; }
void IFC4X3::IfcSegmentedReferenceCurve::getStepLine( std::stringstream& stream ) const
{
	stream << "#" << m_tag << "= IFCSEGMENTEDREFERENCECURVE" << "(";
	writeEntityList( stream, m_Segments );
	stream << ",";
	if( m_SelfIntersect ) { m_SelfIntersect->getStepParameter( stream ); } else { stream << "$"; }
	stream << ",";
	if( m_BaseCurve ) { stream << "#" << m_BaseCurve->m_tag; } else { stream << "$"; }
	stream << ",";
	if( m_EndPoint ) { stream << "#" << m_EndPoint->m_tag; } else { stream << "$"; }
	stream << ");";
}
void IFC4X3::IfcSegmentedReferenceCurve::getStepParameter( std::stringstream& stream, bool /*is_select_type*/ ) const { stream << "#" << m_tag; }
void IFC4X3::IfcSegmentedReferenceCurve::readStepArguments( const std::vector<std::string>& args, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	const size_t num_args = args.size();
	if( num_args != 4 ){ std::stringstream err; err << "Wrong parameter count for entity IfcSegmentedReferenceCurve, expecting 4, having " << num_args << ". Entity ID: " << m_tag << std::endl; throw BuildingException( err.str().c_str() ); }
	readEntityReferenceList( args[0], m_Segments, map, errorStream );
	m_SelfIntersect = IfcLogical::createObjectFromSTEP( args[1], map, errorStream );
	readEntityReference( args[2], m_BaseCurve, map, errorStream );
	readEntityReference( args[3], m_EndPoint, map, errorStream );
}
void IFC4X3::IfcSegmentedReferenceCurve::getAttributes( std::vector<std::pair<std::string, shared_ptr<BuildingObject> > >& vec_attributes ) const
{
	IFC4X3::IfcCompositeCurve::getAttributes( vec_attributes );
	vec_attributes.emplace_back( std::make_pair( "BaseCurve", m_BaseCurve ) );
	vec_attributes.emplace_back( std::make_pair( "EndPoint", m_EndPoint ) );
}
void IFC4X3::IfcSegmentedReferenceCurve::getAttributesInverse( std::vector<std::pair<std::string, shared_ptr<BuildingObject> > >& vec_attributes_inverse ) const
{
	IFC4X3::IfcCompositeCurve::getAttributesInverse( vec_attributes_inverse );
}
void IFC4X3::IfcSegmentedReferenceCurve::setInverseCounterparts( shared_ptr<BuildingEntity> ptr_self_entity )
{
	IfcCompositeCurve::setInverseCounterparts( ptr_self_entity );
}
void IFC4X3::IfcSegmentedReferenceCurve::unlinkFromInverseCounterparts()
{
	IfcCompositeCurve::unlinkFromInverseCounterparts();
}
