/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <sstream>
#include <limits>

#include "ifcpp/Model/AttributeObject.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Model/BuildingGuid.h"
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Writer/WriterUtil.h"
#include "ifcpp/Ifc/IfcAxis2Placement.h"
#include "ifcpp/Ifc/IfcLengthMeasure.h"
#include "ifcpp/Ifc/IfcPresentationLayerAssignment.h"
#include "ifcpp/Ifc/IfcSecondOrderPolynomialSpiral.h"
#include "ifcpp/Ifc/IfcStyledItem.h"

// ENTITY IfcSecondOrderPolynomialSpiral 
IFC4X3::IfcSecondOrderPolynomialSpiral::IfcSecondOrderPolynomialSpiral( int tag ) { m_tag = tag; }
void IFC4X3::IfcSecondOrderPolynomialSpiral::getStepLine( std::stringstream& stream ) const
{
	stream << "#" << m_tag << "= IFCSECONDORDERPOLYNOMIALSPIRAL" << "(";
	if( m_Position ) { m_Position->getStepParameter( stream, true ); } else { stream << "$" ; }
	stream << ",";
	if( m_QuadraticTerm ) { m_QuadraticTerm->getStepParameter( stream ); } else { stream << "$"; }
	stream << ",";
	if( m_LinearTerm ) { m_LinearTerm->getStepParameter( stream ); } else { stream << "$"; }
	stream << ",";
	if( m_ConstantTerm ) { m_ConstantTerm->getStepParameter( stream ); } else { stream << "$"; }
	stream << ");";
}
void IFC4X3::IfcSecondOrderPolynomialSpiral::getStepParameter( std::stringstream& stream, bool /*is_select_type*/ ) const { stream << "#" << m_tag; }
void IFC4X3::IfcSecondOrderPolynomialSpiral::readStepArguments( const std::vector<std::string>& args, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	const size_t num_args = args.size();
	if( num_args != 4 ){ std::stringstream err; err << "Wrong parameter count for entity IfcSecondOrderPolynomialSpiral, expecting 4, having " << num_args << ". Entity ID: " << m_tag << std::endl; throw BuildingException( err.str().c_str() ); }
	m_Position = IfcAxis2Placement::createObjectFromSTEP( args[0], map, errorStream );
	m_QuadraticTerm = IfcLengthMeasure::createObjectFromSTEP( args[1], map, errorStream );
	m_LinearTerm = IfcLengthMeasure::createObjectFromSTEP( args[2], map, errorStream );
	m_ConstantTerm = IfcLengthMeasure::createObjectFromSTEP( args[3], map, errorStream );
}
void IFC4X3::IfcSecondOrderPolynomialSpiral::getAttributes( std::vector<std::pair<std::string, shared_ptr<BuildingObject> > >& vec_attributes ) const
{
	IFC4X3::IfcSpiral::getAttributes( vec_attributes );
	vec_attributes.emplace_back( std::make_pair( "QuadraticTerm", m_QuadraticTerm ) );
	vec_attributes.emplace_back( std::make_pair( "LinearTerm", m_LinearTerm ) );
	vec_attributes.emplace_back( std::make_pair( "ConstantTerm", m_ConstantTerm ) );
}
void IFC4X3::IfcSecondOrderPolynomialSpiral::getAttributesInverse( std::vector<std::pair<std::string, shared_ptr<BuildingObject> > >& vec_attributes_inverse ) const
{
	IFC4X3::IfcSpiral::getAttributesInverse( vec_attributes_inverse );
}
void IFC4X3::IfcSecondOrderPolynomialSpiral::setInverseCounterparts( shared_ptr<BuildingEntity> ptr_self_entity )
{
	IfcSpiral::setInverseCounterparts( ptr_self_entity );
}
void IFC4X3::IfcSecondOrderPolynomialSpiral::unlinkFromInverseCounterparts()
{
	IfcSpiral::unlinkFromInverseCounterparts();
}
