/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "ifcpp/Model/BasicTypes.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Ifc/IfcStructuralActivityAssignmentSelect.h"

// TYPE IfcStructuralActivityAssignmentSelect = SELECT	(IfcElement	,IfcStructuralItem);
shared_ptr<IFC4X3::IfcStructuralActivityAssignmentSelect> IFC4X3::IfcStructuralActivityAssignmentSelect::createObjectFromSTEP( const std::string& arg, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	if( arg.empty() ){ return shared_ptr<IfcStructuralActivityAssignmentSelect>(); }
	if( arg.compare("$")==0 )
	{
		return shared_ptr<IfcStructuralActivityAssignmentSelect>();
	}
	if( arg.compare("*")==0 )
	{
		return shared_ptr<IfcStructuralActivityAssignmentSelect>();
	}
	shared_ptr<IfcStructuralActivityAssignmentSelect> result_object;
	readSelectType( arg, result_object, map, errorStream );
	return result_object;
}
