/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <sstream>
#include <limits>

#include "ifcpp/Model/AttributeObject.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Model/BuildingGuid.h"
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Writer/WriterUtil.h"
#include "ifcpp/Ifc/IfcCurve.h"
#include "ifcpp/Ifc/IfcNonNegativeLengthMeasure.h"
#include "ifcpp/Ifc/IfcParameterValue.h"
#include "ifcpp/Ifc/IfcPositiveLengthMeasure.h"
#include "ifcpp/Ifc/IfcPresentationLayerAssignment.h"
#include "ifcpp/Ifc/IfcStyledItem.h"
#include "ifcpp/Ifc/IfcSweptDiskSolidPolygonal.h"

// ENTITY IfcSweptDiskSolidPolygonal 
IFC4X3::IfcSweptDiskSolidPolygonal::IfcSweptDiskSolidPolygonal( int tag ) { m_tag = tag; }
void IFC4X3::IfcSweptDiskSolidPolygonal::getStepLine( std::stringstream& stream ) const
{
	stream << "#" << m_tag << "= IFCSWEPTDISKSOLIDPOLYGONAL" << "(";
	if( m_Directrix ) { stream << "#" << m_Directrix->m_tag; } else { stream << "$"; }
	stream << ",";
	if( m_Radius ) { m_Radius->getStepParameter( stream ); } else { stream << "$"; }
	stream << ",";
	if( m_InnerRadius ) { m_InnerRadius->getStepParameter( stream ); } else { stream << "$"; }
	stream << ",";
	if( m_StartParam ) { m_StartParam->getStepParameter( stream ); } else { stream << "$"; }
	stream << ",";
	if( m_EndParam ) { m_EndParam->getStepParameter( stream ); } else { stream << "$"; }
	stream << ",";
	if( m_FilletRadius ) { m_FilletRadius->getStepParameter( stream ); } else { stream << "$"; }
	stream << ");";
}
void IFC4X3::IfcSweptDiskSolidPolygonal::getStepParameter( std::stringstream& stream, bool /*is_select_type*/ ) const { stream << "#" << m_tag; }
void IFC4X3::IfcSweptDiskSolidPolygonal::readStepArguments( const std::vector<std::string>& args, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	const size_t num_args = args.size();
	if( num_args != 6 ){ std::stringstream err; err << "Wrong parameter count for entity IfcSweptDiskSolidPolygonal, expecting 6, having " << num_args << ". Entity ID: " << m_tag << std::endl; throw BuildingException( err.str().c_str() ); }
	readEntityReference( args[0], m_Directrix, map, errorStream );
	m_Radius = IfcPositiveLengthMeasure::createObjectFromSTEP( args[1], map, errorStream );
	m_InnerRadius = IfcPositiveLengthMeasure::createObjectFromSTEP( args[2], map, errorStream );
	m_StartParam = IfcParameterValue::createObjectFromSTEP( args[3], map, errorStream );
	m_EndParam = IfcParameterValue::createObjectFromSTEP( args[4], map, errorStream );
	m_FilletRadius = IfcNonNegativeLengthMeasure::createObjectFromSTEP( args[5], map, errorStream );
}
void IFC4X3::IfcSweptDiskSolidPolygonal::getAttributes( std::vector<std::pair<std::string, shared_ptr<BuildingObject> > >& vec_attributes ) const
{
	IFC4X3::IfcSweptDiskSolid::getAttributes( vec_attributes );
	vec_attributes.emplace_back( std::make_pair( "FilletRadius", m_FilletRadius ) );
}
void IFC4X3::IfcSweptDiskSolidPolygonal::getAttributesInverse( std::vector<std::pair<std::string, shared_ptr<BuildingObject> > >& vec_attributes_inverse ) const
{
	IFC4X3::IfcSweptDiskSolid::getAttributesInverse( vec_attributes_inverse );
}
void IFC4X3::IfcSweptDiskSolidPolygonal::setInverseCounterparts( shared_ptr<BuildingEntity> ptr_self_entity )
{
	IfcSweptDiskSolid::setInverseCounterparts( ptr_self_entity );
}
void IFC4X3::IfcSweptDiskSolidPolygonal::unlinkFromInverseCounterparts()
{
	IfcSweptDiskSolid::unlinkFromInverseCounterparts();
}
