/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <sstream>
#include <limits>

#include "ifcpp/Model/AttributeObject.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Model/BuildingGuid.h"
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Writer/WriterUtil.h"
#include "ifcpp/Ifc/IfcAxis2Placement3D.h"
#include "ifcpp/Ifc/IfcPresentationLayerAssignment.h"
#include "ifcpp/Ifc/IfcProfileDef.h"
#include "ifcpp/Ifc/IfcStyledItem.h"
#include "ifcpp/Ifc/IfcSweptSurface.h"

// ENTITY IfcSweptSurface 
IFC4X3::IfcSweptSurface::IfcSweptSurface( int tag ) { m_tag = tag; }
void IFC4X3::IfcSweptSurface::getStepLine( std::stringstream& stream ) const
{
	stream << "#" << m_tag << "= IFCSWEPTSURFACE" << "(";
	if( m_SweptCurve ) { stream << "#" << m_SweptCurve->m_tag; } else { stream << "$"; }
	stream << ",";
	if( m_Position ) { stream << "#" << m_Position->m_tag; } else { stream << "$"; }
	stream << ");";
}
void IFC4X3::IfcSweptSurface::getStepParameter( std::stringstream& stream, bool /*is_select_type*/ ) const { stream << "#" << m_tag; }
void IFC4X3::IfcSweptSurface::readStepArguments( const std::vector<std::string>& args, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	const size_t num_args = args.size();
	if( num_args != 2 ){ std::stringstream err; err << "Wrong parameter count for entity IfcSweptSurface, expecting 2, having " << num_args << ". Entity ID: " << m_tag << std::endl; throw BuildingException( err.str().c_str() ); }
	readEntityReference( args[0], m_SweptCurve, map, errorStream );
	readEntityReference( args[1], m_Position, map, errorStream );
}
void IFC4X3::IfcSweptSurface::getAttributes( std::vector<std::pair<std::string, shared_ptr<BuildingObject> > >& vec_attributes ) const
{
	IFC4X3::IfcSurface::getAttributes( vec_attributes );
	vec_attributes.emplace_back( std::make_pair( "SweptCurve", m_SweptCurve ) );
	vec_attributes.emplace_back( std::make_pair( "Position", m_Position ) );
}
void IFC4X3::IfcSweptSurface::getAttributesInverse( std::vector<std::pair<std::string, shared_ptr<BuildingObject> > >& vec_attributes_inverse ) const
{
	IFC4X3::IfcSurface::getAttributesInverse( vec_attributes_inverse );
}
void IFC4X3::IfcSweptSurface::setInverseCounterparts( shared_ptr<BuildingEntity> ptr_self_entity )
{
	IfcSurface::setInverseCounterparts( ptr_self_entity );
}
void IFC4X3::IfcSweptSurface::unlinkFromInverseCounterparts()
{
	IfcSurface::unlinkFromInverseCounterparts();
}
