/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "ifcpp/Model/BasicTypes.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Ifc/IfcSolidOrShell.h"

// TYPE IfcSolidOrShell = SELECT	(IfcClosedShell	,IfcSolidModel);
shared_ptr<IFC4X3::IfcSolidOrShell> IFC4X3::IfcSolidOrShell::createObjectFromSTEP( const std::string& arg, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	if( arg.empty() ){ return shared_ptr<IfcSolidOrShell>(); }
	if( arg.compare("$")==0 )
	{
		return shared_ptr<IfcSolidOrShell>();
	}
	if( arg.compare("*")==0 )
	{
		return shared_ptr<IfcSolidOrShell>();
	}
	shared_ptr<IfcSolidOrShell> result_object;
	readSelectType( arg, result_object, map, errorStream );
	return result_object;
}
