/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "ifcpp/Model/BasicTypes.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Ifc/IfcSpecularExponent.h"
#include "ifcpp/Ifc/IfcSpecularRoughness.h"
#include "ifcpp/Ifc/IfcSpecularHighlightSelect.h"

// TYPE IfcSpecularHighlightSelect = SELECT	(IfcSpecularExponent	,IfcSpecularRoughness);
shared_ptr<IFC4X3::IfcSpecularHighlightSelect> IFC4X3::IfcSpecularHighlightSelect::createObjectFromSTEP( const std::string& arg, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	if( arg.empty() ){ return shared_ptr<IfcSpecularHighlightSelect>(); }
	if( arg.compare("$")==0 )
	{
		return shared_ptr<IfcSpecularHighlightSelect>();
	}
	if( arg.compare("*")==0 )
	{
		return shared_ptr<IfcSpecularHighlightSelect>();
	}
	shared_ptr<IfcSpecularHighlightSelect> result_object;
	readSelectType( arg, result_object, map, errorStream );
	return result_object;
}
