/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "ifcpp/Model/BasicTypes.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Ifc/IfcDescriptiveMeasure.h"
#include "ifcpp/Ifc/IfcLengthMeasure.h"
#include "ifcpp/Ifc/IfcNormalisedRatioMeasure.h"
#include "ifcpp/Ifc/IfcPositiveLengthMeasure.h"
#include "ifcpp/Ifc/IfcPositiveRatioMeasure.h"
#include "ifcpp/Ifc/IfcRatioMeasure.h"
#include "ifcpp/Ifc/IfcSizeSelect.h"

// TYPE IfcSizeSelect = SELECT	(IfcDescriptiveMeasure	,IfcLengthMeasure	,IfcNormalisedRatioMeasure	,IfcPositiveLengthMeasure	,IfcPositiveRatioMeasure	,IfcRatioMeasure);
shared_ptr<IFC4X3::IfcSizeSelect> IFC4X3::IfcSizeSelect::createObjectFromSTEP( const std::string& arg, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	if( arg.empty() ){ return shared_ptr<IfcSizeSelect>(); }
	if( arg.compare("$")==0 )
	{
		return shared_ptr<IfcSizeSelect>();
	}
	if( arg.compare("*")==0 )
	{
		return shared_ptr<IfcSizeSelect>();
	}
	shared_ptr<IfcSizeSelect> result_object;
	readSelectType( arg, result_object, map, errorStream );
	return result_object;
}
