/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */

#include <sstream>
#include <limits>
#include <map>
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Writer/WriterUtil.h"
#include "ifcpp/Model/BasicTypes.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Ifc/IfcTextAlignment.h"

// TYPE IfcTextAlignment = STRING;
IFC4X3::IfcTextAlignment::IfcTextAlignment( std::string value ) { m_value = value; }
void IFC4X3::IfcTextAlignment::getStepParameter( std::stringstream& stream, bool is_select_type ) const
{
	if( is_select_type ) { stream << "IFCTEXTALIGNMENT("; }
	stream << "'" << encodeStepString( m_value ) << "'";
	if( is_select_type ) { stream << ")"; }
}
shared_ptr<IFC4X3::IfcTextAlignment> IFC4X3::IfcTextAlignment::createObjectFromSTEP( const std::string& arg, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	if( arg.compare( "$" ) == 0 ) { return shared_ptr<IfcTextAlignment>(); }
	if( arg.compare( "*" ) == 0 ) { return shared_ptr<IfcTextAlignment>(); }
	shared_ptr<IfcTextAlignment> type_object( new IfcTextAlignment() );
	readString( arg, type_object->m_value );
	return type_object;
}
