/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "ifcpp/Model/BasicTypes.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Ifc/IfcDuration.h"
#include "ifcpp/Ifc/IfcRatioMeasure.h"
#include "ifcpp/Ifc/IfcTimeOrRatioSelect.h"

// TYPE IfcTimeOrRatioSelect = SELECT	(IfcDuration	,IfcRatioMeasure);
shared_ptr<IFC4X3::IfcTimeOrRatioSelect> IFC4X3::IfcTimeOrRatioSelect::createObjectFromSTEP( const std::string& arg, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	if( arg.empty() ){ return shared_ptr<IfcTimeOrRatioSelect>(); }
	if( arg.compare("$")==0 )
	{
		return shared_ptr<IfcTimeOrRatioSelect>();
	}
	if( arg.compare("*")==0 )
	{
		return shared_ptr<IfcTimeOrRatioSelect>();
	}
	shared_ptr<IfcTimeOrRatioSelect> result_object;
	readSelectType( arg, result_object, map, errorStream );
	return result_object;
}
