/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "ifcpp/Model/BasicTypes.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Ifc/IfcTextFontSelect.h"

// TYPE IfcTextFontSelect = SELECT	(IfcExternallyDefinedTextFont	,IfcPreDefinedTextFont);
shared_ptr<IFC4X3::IfcTextFontSelect> IFC4X3::IfcTextFontSelect::createObjectFromSTEP( const std::string& arg, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	if( arg.empty() ){ return shared_ptr<IfcTextFontSelect>(); }
	if( arg.compare("$")==0 )
	{
		return shared_ptr<IfcTextFontSelect>();
	}
	if( arg.compare("*")==0 )
	{
		return shared_ptr<IfcTextFontSelect>();
	}
	shared_ptr<IfcTextFontSelect> result_object;
	readSelectType( arg, result_object, map, errorStream );
	return result_object;
}
