/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */

#include <sstream>
#include <limits>
#include <map>
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Writer/WriterUtil.h"
#include "ifcpp/Model/BasicTypes.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Ifc/IfcSimpleValue.h"
#include "ifcpp/Ifc/IfcTimeStamp.h"

// TYPE IfcTimeStamp = INTEGER;
IFC4X3::IfcTimeStamp::IfcTimeStamp( int value ) { m_value = value; }
void IFC4X3::IfcTimeStamp::getStepParameter( std::stringstream& stream, bool is_select_type ) const
{
	if( is_select_type ) { stream << "IFCTIMESTAMP("; }
	stream << m_value;
	if( is_select_type ) { stream << ")"; }
}
shared_ptr<IFC4X3::IfcTimeStamp> IFC4X3::IfcTimeStamp::createObjectFromSTEP( const std::string& arg, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	if( arg.compare( "$" ) == 0 ) { return shared_ptr<IfcTimeStamp>(); }
	if( arg.compare( "*" ) == 0 ) { return shared_ptr<IfcTimeStamp>(); }
	shared_ptr<IfcTimeStamp> type_object( new IfcTimeStamp() );
	readInteger( arg, type_object->m_value );
	return type_object;
}
