/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "ifcpp/Model/BasicTypes.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Ifc/IfcUnit.h"

// TYPE IfcUnit = SELECT	(IfcDerivedUnit	,IfcMonetaryUnit	,IfcNamedUnit);
shared_ptr<IFC4X3::IfcUnit> IFC4X3::IfcUnit::createObjectFromSTEP( const std::string& arg, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	if( arg.empty() ){ return shared_ptr<IfcUnit>(); }
	if( arg.compare("$")==0 )
	{
		return shared_ptr<IfcUnit>();
	}
	if( arg.compare("*")==0 )
	{
		return shared_ptr<IfcUnit>();
	}
	shared_ptr<IfcUnit> result_object;
	readSelectType( arg, result_object, map, errorStream );
	return result_object;
}
