/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "ifcpp/Model/BasicTypes.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Ifc/IfcBoolean.h"
#include "ifcpp/Ifc/IfcWarpingMomentMeasure.h"
#include "ifcpp/Ifc/IfcWarpingStiffnessSelect.h"

// TYPE IfcWarpingStiffnessSelect = SELECT	(IfcBoolean	,IfcWarpingMomentMeasure);
shared_ptr<IFC4X3::IfcWarpingStiffnessSelect> IFC4X3::IfcWarpingStiffnessSelect::createObjectFromSTEP( const std::string& arg, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	if( arg.empty() ){ return shared_ptr<IfcWarpingStiffnessSelect>(); }
	if( arg.compare("$")==0 )
	{
		return shared_ptr<IfcWarpingStiffnessSelect>();
	}
	if( arg.compare("*")==0 )
	{
		return shared_ptr<IfcWarpingStiffnessSelect>();
	}
	shared_ptr<IfcWarpingStiffnessSelect> result_object;
	readSelectType( arg, result_object, map, errorStream );
	return result_object;
}
