/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */

#include <sstream>
#include <limits>
#include <map>
#include "ifcpp/Reader/ReaderUtil.h"
#include "ifcpp/Writer/WriterUtil.h"
#include "ifcpp/Model/BasicTypes.h"
#include "ifcpp/Model/BuildingException.h"
#include "ifcpp/Ifc/IfcDerivedMeasureValue.h"
#include "ifcpp/Ifc/IfcWarpingStiffnessSelect.h"
#include "ifcpp/Ifc/IfcWarpingMomentMeasure.h"

// TYPE IfcWarpingMomentMeasure = REAL;
IFC4X3::IfcWarpingMomentMeasure::IfcWarpingMomentMeasure( double value ) { m_value = value; }
void IFC4X3::IfcWarpingMomentMeasure::getStepParameter( std::stringstream& stream, bool is_select_type ) const
{
	if( is_select_type ) { stream << "IFCWARPINGMOMENTMEASURE("; }
	appendRealWithoutTrailingZeros( stream, m_value );
	if( is_select_type ) { stream << ")"; }
}
shared_ptr<IFC4X3::IfcWarpingMomentMeasure> IFC4X3::IfcWarpingMomentMeasure::createObjectFromSTEP( const std::string& arg, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	if( arg.compare( "$" ) == 0 ) { return shared_ptr<IfcWarpingMomentMeasure>(); }
	if( arg.compare( "*" ) == 0 ) { return shared_ptr<IfcWarpingMomentMeasure>(); }
	shared_ptr<IfcWarpingMomentMeasure> type_object( new IfcWarpingMomentMeasure() );
	readReal( arg, type_object->m_value );
	return type_object;
}
